name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
        id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test
      - uses: actions/upload-artifact@v3
        with:
          name: sigstore-artifacts
          path: |
            artifact.zip
            artifact.zip.sigstore